package com.paperboard.server.events;

public enum EventType {

    // ---- MSG RECEIVED FROM CLIENTS
    IDENTIFY,
    JOIN_BOARD,
    LEAVE_BOARD,
    CREATE_OBJECT,
    EDIT_OBJECT,
    LOCK_OBJECT,
    UNLOCK_OBJECT,
    CHAT_MESSAGE,
    DELETE_OBJECT,

    // ---- INTERNAL DECISIONS
    DRAWER_CONNECTED,
    DRAWER_IDENTIFIED,
    DRAWER_DISCONNECTED,
    DRAWER_JOINED_BOARD,
    DRAWER_LEFT_BOARD,
    OBJECT_CREATED,
    OBJECT_EDITED,
    OBJECT_DELETED,
    OBJECT_LOCKED,
    OBJECT_UNLOCKED;
}
