package com.paperboard.server.events;

public enum EventType {

    // ---- REQUESTS RECEIVED FROM CLIENTS
    ASK_IDENTITY,
    ASK_JOIN_BOARD,
    ASK_LEAVE_BOARD,
    ASK_CREATE_OBJECT,
    ASK_EDIT_OBJECT,
    ASK_DELETE_OBJECT,
    ASK_LOCK_OBJECT,
    ASK_UNLOCK_OBJECT,
    CHAT_MESSAGE,

    // ---- INTERNAL DECISIONS
    DRAWER_CONNECTED,
    DRAWER_DISCONNECTED,
    DRAWER_IDENTIFIED,
    DRAWER_JOINED_BOARD,
    DRAWER_LEFT_BOARD,
    OBJECT_CREATED,
    OBJECT_EDITED,
    OBJECT_DELETED,
    OBJECT_LOCKED,
    OBJECT_UNLOCKED;
}
